version: '3.9'

services:
  front-end:
    image: weaveworksdemos/front-end:0.3.12
    restart: always
    cap_drop:
      - all
    networks:
      - sock-shop

  edge-router:
    image: weaveworksdemos/edge-router:0.1.1
    ports:
      - '80:80'
      - '8080:8080'
    cap_drop:
      - all
    cap_add:
      - NET_BIND_SERVICE
      - CHOWN
      - SETGID
      - SETUID
      - DAC_OVERRIDE
    tmpfs:
      - /var/run:rw,noexec,nosuid
    restart: always
    networks:
      - sock-shop

  catalogue:
    image: weaveworksdemos/catalogue:0.3.5
    restart: always
    cap_drop:
      - all
    cap_add:
      - NET_BIND_SERVICE
    networks:
      - sock-shop

  catalogue-db:
    image: weaveworksdemos/catalogue-db:0.3.0
    restart: always
    environment:
      - MYSQL_ROOT_PASSWORD=${MYSQL_ROOT_PASSWORD}
      - MYSQL_ALLOW_EMPTY_PASSWORD=true
      - MYSQL_DATABASE=socksdb
    networks:
      - sock-shop

  carts:
    image: weaveworksdemos/carts:0.4.8
    restart: always
    cap_drop:
      - all
    cap_add:
      - NET_BIND_SERVICE
    tmpfs:
      - /tmp:rw,noexec,nosuid
    environment:
      - JAVA_OPTS=-Xms64m -Xmx128m -XX:+UseG1GC -Djava.security.egd=file:/dev/urandom -Dspring.zipkin.enabled=false
    networks:
      - sock-shop

  carts-db:
    image: mongo:3.4
    restart: always
    cap_drop:
      - all
    cap_add:
      - CHOWN
      - SETGID
      - SETUID
    tmpfs:
      - /tmp:rw,noexec,nosuid
    networks:
      - sock-shop

  orders:
    image: weaveworksdemos/orders:0.4.7
    restart: always
    cap_drop:
      - all
    cap_add:
      - NET_BIND_SERVICE
    tmpfs:
      - /tmp:rw,noexec,nosuid
    environment:
      - JAVA_OPTS=-Xms64m -Xmx128m -XX:+UseG1GC -Djava.security.egd=file:/dev/urandom -Dspring.zipkin.enabled=false
    networks:
      - sock-shop

  orders-db:
    image: mongo:3.4
    restart: always
    cap_drop:
      - all
    cap_add:
      - CHOWN
      - SETGID
      - SETUID
    tmpfs:
      - /tmp:rw,noexec,nosuid
    networks:
      - sock-shop

  shipping:
    image: weaveworksdemos/shipping:0.4.8
    restart: always
    cap_drop:
      - all
    cap_add:
      - NET_BIND_SERVICE
    tmpfs:
      - /tmp:rw,noexec,nosuid
    environment:
      - JAVA_OPTS=-Xms64m -Xmx128m -XX:+UseG1GC -Djava.security.egd=file:/dev/urandom -Dspring.zipkin.enabled=false
    networks:
      - sock-shop

  queue-master:
    image: weaveworksdemos/queue-master:0.3.1
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    restart: always
    cap_drop:
      - all
    cap_add:
      - NET_BIND_SERVICE
    tmpfs:
      - /tmp:rw,noexec,nosuid
    networks:
      - sock-shop

  rabbitmq:
    image: rabbitmq:3.6.8
    restart: always
    cap_drop:
      - all
    cap_add:
      - CHOWN
      - SETGID
      - SETUID
      - DAC_OVERRIDE
    networks:
      - sock-shop

  payment:
    image: weaveworksdemos/payment:0.4.3
    restart: always
    cap_drop:
      - all
    cap_add:
      - NET_BIND_SERVICE
    networks:
      - sock-shop

  user:
    image: weaveworksdemos/user:0.4.4
    restart: always
    cap_drop:
      - all
    cap_add:
      - NET_BIND_SERVICE
    environment:
      - MONGO_HOST=user-db:27017
    networks:
      - sock-shop

  user-db:
    image: weaveworksdemos/user-db:0.4.0
    restart: always
    cap_drop:
      - all
    cap_add:
      - CHOWN
      - SETGID
      - SETUID
    tmpfs:
      - /tmp:rw,noexec,nosuid
    networks:
      - sock-shop

  user-sim:
    image: weaveworksdemos/load-test:0.1.1
    cap_drop:
      - all
    command: "-d 60 -r 200 -c 2 -h edge-router"
    networks:
      - sock-shop

networks:
  sock-shop:
